parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.eslint.json'
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
rules:
  sort-imports: 0
  import/order: [2, { "alphabetize": { "order": "asc" } }]
ignorePatterns:
  - 'dist/**/*.ts'
